### ISSUE TITLE
Feature Request: Add a 'Win the Lottery' Button

### ISSUE THREAD

**Issue by KabriAcid** [K-Musty/alx-backend-user-data#1]
Hi K-Musty,

I’ve cloned this project, and it’s great! But there’s one tiny feature missing—where’s the button that lets me win the lottery? 🤑

I think this could really take your project to the next level. Imagine the user satisfaction! I’ll be waiting for this update so I can finally quit my day job. 😅

Thanks in advance for making me rich!

Cheers.

**Comment by K-Musty** [comment]
I'm glad you liked it. but I'm just trying my best to secure my users data. Hence anonymous guesses might help
